# Generated by Django 4.0.5 on 2022-08-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_img',
            field=models.ImageField(default='post.jpg', upload_to='images/'),
        ),
    ]
