# Generated by Django 4.0.5 on 2022-07-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0002_alter_ingredientlists_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='Title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredients_list',
            new_name='ingredientList',
        ),
    ]
