# Generated by Django 4.0.5 on 2022-08-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0002_recipes_recipe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userbookmarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbookmark_Recipe', to='recipesite.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_img',
            field=models.ImageField(default='post.jpeg', upload_to='images/'),
        ),
    ]
