# Generated by Django 4.0.5 on 2022-07-28 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0003_rename_title_ingredients_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredientList',
            new_name='ingredients_list',
        ),
        migrations.AlterField(
            model_name='ingredientlists',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientlists',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingr_name', to='recipesite.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
