# Generated by Django 4.0.5 on 2022-07-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0004_rename_ingredientlist_recipes_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlists',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientlists',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientlists',
            name='unitId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cookTimeHour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cookTimeMin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prepTimeHour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prepTimeMin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='servingQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='skillLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
