# Generated by Django 4.0.5 on 2022-07-28 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0005_alter_ingredientlists_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientlists', to='recipesite.ingredientlists'),
        ),
    ]
