# Generated by Django 4.0.5 on 2022-07-29 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0006_remove_recipes_ingredients_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients_list',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='userId',
        ),
        migrations.AddField(
            model_name='ingredientlists',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesite.recipes'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient',
            field=models.ManyToManyField(null=True, through='recipesite.IngredientLists', to='recipesite.ingredients'),
        ),
    ]
